export const callOutBlocks = [
	{
		has_children: false,
		archived: false,
		type: "callout",
		callout: {
			rich_text: [
				{
					type: "text",
					text: {
						content: "This is a simple call out",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "This is a simple call out",
					href: null,
				},
			],
			icon: {
				type: "emoji",
				emoji: "🔑",
			},
			color: "gray_background",
		},
	},
	{
		has_children: false,
		archived: false,
		type: "callout",
		callout: {
			rich_text: [
				{
					type: "text",
					text: {
						content: "This is a",
						link: null,
					},
					annotations: {
						bold: true,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "This is a",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "call out with",
						link: null,
					},
					annotations: {
						bold: false,
						italic: true,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "call out with",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "empty blocks",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: true,
						code: false,
						color: "default",
					},
					plain_text: "empty blocks",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "and all",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: true,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "and all",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "styling within",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: true,
						color: "default",
					},
					plain_text: "styling within",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "the call out",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "yellow",
					},
					plain_text: "the call out",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "\n\n",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "\n\n",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "There should",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "green_background",
					},
					plain_text: "There should",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "be a new line",
						link: {
							url: "https://google.com",
						},
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "be a new line",
					href: "https://google.com",
				},
				{
					type: "text",
					text: {
						content: " above this line",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " above this line",
					href: null,
				},
			],
			icon: {
				type: "emoji",
				emoji: "🔑",
			},
			color: "gray_background",
		},
	},
];
