export const codeBlocks = [
	{
		has_children: false,
		archived: false,
		type: "code",
		code: {
			caption: [
				{
					type: "text",
					text: {
						content: "this",
						link: null,
					},
					annotations: {
						bold: true,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "this",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "is",
						link: null,
					},
					annotations: {
						bold: false,
						italic: true,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "is",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "a",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: true,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "a",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "cool",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "brown",
					},
					plain_text: "cool",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "caption",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "yellow_background",
					},
					plain_text: "caption",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "under",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "purple_background",
					},
					plain_text: "under",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "a code",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: true,
						code: false,
						color: "default",
					},
					plain_text: "a code",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "block",
						link: {
							url: "https://google.com",
						},
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "block",
					href: "https://google.com",
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "equation",
					equation: {
						expression: "below",
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "below",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " javascript",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " javascript",
					href: null,
				},
			],
			rich_text: [
				{
					type: "text",
					text: {
						content:
							"export default function App({ Component, pageProps }) {\n",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: true,
						code: false,
						color: "default",
					},
					plain_text:
						"export default function App({ Component, pageProps }) {\n",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "\treturn (\n\t\t",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "\treturn (\n\t\t",
					href: null,
				},
				{
					type: "text",
					text: {
						content:
							"<>\n\t\t\t<Component {...pageProps} />;\n\t\t\t<Footer />\n\t\t</>",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: true,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text:
						"<>\n\t\t\t<Component {...pageProps} />;\n\t\t\t<Footer />\n\t\t</>",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "\n\t);\n}",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "\n\t);\n}",
					href: null,
				},
			],
			language: "javascript",
		},
	},
	{
		has_children: false,
		archived: false,
		type: "code",
		code: {
			caption: [
				{
					type: "text",
					text: {
						content: "this",
						link: null,
					},
					annotations: {
						bold: true,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "this",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "is",
						link: null,
					},
					annotations: {
						bold: false,
						italic: true,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "is",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "a",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: true,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "a",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "cool",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "brown",
					},
					plain_text: "cool",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "caption",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "yellow_background",
					},
					plain_text: "caption",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "under",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "purple_background",
					},
					plain_text: "under",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "a code",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: true,
						code: false,
						color: "default",
					},
					plain_text: "a code",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "text",
					text: {
						content: "block",
						link: {
							url: "https://google.com",
						},
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "block",
					href: "https://google.com",
				},
				{
					type: "text",
					text: {
						content: " ",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " ",
					href: null,
				},
				{
					type: "equation",
					equation: {
						expression: "below",
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "below",
					href: null,
				},
				{
					type: "text",
					text: {
						content: " javascript",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: " javascript",
					href: null,
				},
			],
			rich_text: [
				{
					type: "text",
					text: {
						content:
							"export default function App({ Component, pageProps }) {\n\treturn (\n\t\t<>\n\t\t\t<Component {...pageProps} />;\n\t\t\t<Footer />\n\t\t</>\n\t);\n}",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text:
						"export default function App({ Component, pageProps }) {\n\treturn (\n\t\t<>\n\t\t\t<Component {...pageProps} />;\n\t\t\t<Footer />\n\t\t</>\n\t);\n}",
					href: null,
				},
			],
			language: "javascript",
		},
	},
	{
		has_children: false,
		archived: false,
		type: "code",
		code: {
			caption: [],
			rich_text: [
				{
					type: "text",
					text: {
						content: 'def hello_world():\n    print("hello world")',
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: 'def hello_world():\n    print("hello world")',
					href: null,
				},
			],
			language: "python",
		},
	},
	{
		has_children: false,
		archived: false,
		type: "code",
		code: {
			caption: [],
			rich_text: [
				{
					type: "text",
					text: {
						content:
							'class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!"); \n    }\n}',
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text:
						'class HelloWorld {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!"); \n    }\n}',
					href: null,
				},
			],
			language: "java",
		},
	},
	{
		has_children: false,
		archived: false,
		type: "code",
		code: {
			caption: [],
			rich_text: [
				{
					type: "text",
					text: {
						content: "#!/bin/bash\n\necho Hello World!",
						link: null,
					},
					annotations: {
						bold: false,
						italic: false,
						strikethrough: false,
						underline: false,
						code: false,
						color: "default",
					},
					plain_text: "#!/bin/bash\n\necho Hello World!",
					href: null,
				},
			],
			language: "bash",
		},
	},
];
