name: Build, Publish to NPM and Deploy to Chromatic
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: yarn install
      - name: Build package with Rollup
        run: yarn rollup
      - name: Release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

  chromatic-deployment:
    # Operating System
    runs-on: ubuntu-latest
    needs: build-and-publish
    # Job steps
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
        env:
          NPM_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}